### ISSUE TITLE
Currency tiker worker

### ISSUE THREAD

**Issue by nazgull08** [hexresearch/hexstody#164]
Worker get tickers for active currencies and store it in Storage, it updates every minute
Worker should be created as client, like btc_client and have handlers for every currency (despite GTECH)

**Comment by LeMarwin** [comment]
We already have separate runtime-only state for hexstody-public at [state.rs](https://github.com/hexresearch/hexstody/blob/master/hexstody-public/src/state.rs).

Move it to a core type module e.g. ``hexstody-api::runtime``, add tickers to ``RuntimeState``

Create a new API handler for tickers: a package ``hexstody-tickers``. Design it like public/operator API: public ``serve_api`` function, that takes all necessary stuff + an ``Arc<Mutex<RuntimeState>>``

Pass ``Arc<Mutex<RuntimeState>>`` also to public API.

Serve ticker API alongside public and operator's API

Adjust the frontend to query separate API for tickers
